version: 2
# Override bad release in jboss.org repo.
registries:
  maven-central:
    type: maven-repository
    url: https://repo.maven.apache.org/maven2/
    replaces-base: true
updates:
  - package-ecosystem: maven
    directory: "/"
    registries:
      - maven-central
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: org.apache.tomcat:tomcat-catalina
      - dependency-name: org.apache.tomcat:tomcat-coyote
      - dependency-name: org.apache.tomcat:tomcat-servlet-api
      - dependency-name: org.apache.tomcat:tomcat-util
  - package-ecosystem: maven
    directory: "/container/tomcat-8.5"
    registries:
      - maven-central
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: org.apache.tomcat:tomcat-catalina
        versions:
          - ">= 9"
      - dependency-name: org.apache.tomcat:tomcat-coyote
        versions:
          - ">= 9"
      - dependency-name: org.apache.tomcat:tomcat-util
        versions:
          - ">= 9"
  - package-ecosystem: maven
    directory: "/container/tomcat-9.0"
    registries:
      - maven-central
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: org.apache.tomcat:tomcat-catalina
        versions:
          - ">= 10"
      - dependency-name: org.apache.tomcat:tomcat-coyote
        versions:
          - ">= 10"
      - dependency-name: org.apache.tomcat:tomcat-util
        versions:
          - ">= 10"
  - package-ecosystem: maven
    directory: "/container/tomcat-10.0"
    registries:
      - maven-central
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: org.apache.tomcat:tomcat-catalina
        versions:
          - ">= 10.1"
      - dependency-name: org.apache.tomcat:tomcat-coyote
        versions:
          - ">= 10.1"
      - dependency-name: org.apache.tomcat:tomcat-util
        versions:
          - ">= 10.1"
  - package-ecosystem: maven
    directory: "/container/tomcat-10.1"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: org.apache.tomcat:tomcat-catalina
        versions:
          - ">= 11"
      - dependency-name: org.apache.tomcat:tomcat-coyote
        versions:
          - ">= 11"
      - dependency-name: org.apache.tomcat:tomcat-util
        versions:
          - ">= 11"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
